### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by merajali294** [wpquads/quick-adsense-reloaded#444]
[07-Dec-2021 12:43:26 UTC] PHP Fatal error:  Uncaught TypeError: Cannot access offset of type string on string in C:\xampp\htdocs\w1\wp-content\plugins\quick-adsense-reloaded\admin\includes\widget.php:102
Stack trace:
#0 C:\xampp\htdocs\w1\wp-includes\class-wp-widget.php(534): Quads_Ads_Widget->form(Array)
#1 C:\xampp\htdocs\w1\wp-admin\includes\widgets.php(274): WP_Widget->form_callback(Array)
#2 C:\xampp\htdocs\w1\wp-includes\class-wp-customize-widgets.php(1122): wp_widget_control(Array, Array)
#3 C:\xampp\htdocs\w1\wp-includes\class-wp-customize-widgets.php(1070): WP_Customize_Widgets->get_widget_control(Array)
#4 C:\xampp\htdocs\w1\wp-includes\class-wp-customize-widgets.php(712): WP_Customize_Widgets->get_available_widgets()
#5 C:\xampp\htdocs\w1\wp-includes\class-wp-hook.php(303): WP_Customize_Widgets->enqueue_scripts('')
#6 C:\xampp\htdocs\w1\wp-includes\class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array)
#7 C:\xampp\htdocs\w1\wp-includes\plugin.php(470): WP_Hook->do_action(Array)
#8 C:\xampp\htdocs\w1\wp-admin\customize.php(123): do_action('customize_contr...')
#9 {main}
  thrown in C:\xampp\htdocs\w1\wp-content\plugins\quick-adsense-reloaded\admin\includes\widget.php on line 102

**Comment by merajali294** [comment]
Pushed in 2.0.37
